#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Mon May  7 08:11:51 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "Frequency:   ")
        self.text_ctrl_frequency = wx.TextCtrl(self, wx.ID_ANY, "1")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "Amplitude:   ")
        self.text_ctrl_amplitude = wx.TextCtrl(self, wx.ID_ANY, "1")
        self.label_3 = wx.StaticText(self, wx.ID_ANY, "Phase shift:  ")
        self.text_ctrl_phase = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.label_4 = wx.StaticText(self, wx.ID_ANY, "Sampling period: ")
        self.text_ctrl_sampling = wx.TextCtrl(self, wx.ID_ANY, "0.1")
        self.label_5 = wx.StaticText(self, wx.ID_ANY, "Noise power:  ")
        self.text_ctrl_noise = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.label_6 = wx.StaticText(self, wx.ID_ANY, "Start time:  ")
        self.text_ctrl_start = wx.TextCtrl(self, wx.ID_ANY, "0")
        self.label_7 = wx.StaticText(self, wx.ID_ANY, "End time:  ")
        self.text_ctrl_end = wx.TextCtrl(self, wx.ID_ANY, "100")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Generate signal")
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.save_data = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, "Save data", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.save_data)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Quit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.generate, self.button_1)
        self.Bind(wx.EVT_MENU, self.save, self.save_data)
        self.Bind(wx.EVT_MENU, self.quit, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Harmonic signal generator")
        self.panel_1.SetMinSize((640,480))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(7, 2, 0, 0)
        grid_sizer_2.Add(self.label_1, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_frequency, 0, 0, 0)
        grid_sizer_2.Add(self.label_2, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_amplitude, 0, 0, 0)
        grid_sizer_2.Add(self.label_3, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_phase, 0, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_sampling, 0, 0, 0)
        grid_sizer_2.Add(self.label_5, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_noise, 0, 0, 0)
        grid_sizer_2.Add(self.label_6, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_start, 0, 0, 0)
        grid_sizer_2.Add(self.label_7, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_end, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.panel_1.SetSizer(sizer_1)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def generate(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'generate' not implemented!"
        event.Skip()

    def save(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'save' not implemented!"
        event.Skip()

    def quit(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'quit' not implemented!"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()